### ISSUE TITLE
namespaces

### ISSUE THREAD

**Issue by dbecvarik** [prgcont/workshop-k8s#26]
Every sample should be run in personalized namespace - export variable? 
Is there an equivalent of oc project switching in kubectl?

**Comment by jwerak** [comment]
There is a [solution to update kube/config context](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#setting-the-namespace-preference): 

```
$ kubectl config set-context $(kubectl config current-context) --namespace=<insert-namespace-name-here>
# Validate it
$ kubectl config view | grep namespace:
```

**Comment by jwerak** [comment]
We are setting separate environmnets for each user with custom context. 
The example of kubeconfig is: 

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: CERT_DATA
    server: https://MASTER:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: USERS_NAMESPACE
    user: martinb-martinb-kubernetes
  name: martinb-martinb-kubernetes
current-context: martinb-martinb-kubernetes
kind: Config
preferences: {}
users:
- name: martinb-martinb-kubernetes
  user:
    token: TOKEN

```
